### ISSUE TITLE
Failed to open a connection to the backend - AppsMan on PAS 2.5.7

### ISSUE THREAD

**Issue by sritimmaraju** [pivotal-cf/docs-pivotalcf-console#11]
Failed to open a connection to the backend. If your Cloud Foundry is using a self-signed certificate, accept the certificate in the following window. Otherwise, contact your administrator immediately.

<img width="1207" alt="Screen Shot 2019-07-31 at 10 04 11 AM" src="https://user-images.githubusercontent.com/43353148/62223596-d7d5b600-b37a-11e9-8243-f8408360374d.png">

**Comment by mlimonczenko** [comment]
Hello @sritimmaraju,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
