### ISSUE TITLE
Apache NIFI as a PCF service

### ISSUE THREAD

**Issue by MohanBunny** [pivotal-cf/docs-pivotalcf-console#5]
Hi,
I am just curious to know  that is there any way to use the Apache NIFI as a service in PCF.
If we can then how we can use it.
What are the steps that we should follow.
Please give us your valuable suggestions.
Thank you.
Mohan.V

**Comment by bentarnoff** [comment]
Hi @MohanBunny I'm afraid our documentation does not offer any specific information about how to integrate Apache NIFI with PCF, but you should be able to configure syslog forwarding to drain PCF VM logs to your Apache NIFI instance. The "System Logging" section in the Elastic Runtime tile lets operators configure a syslog drain. The documentation on this section is differentiated by IaaS, but for example, see our AWS documentation [here](https://docs.pivotal.io/pivotalcf/1-7/customizing/cloudform-er-config.html#sys-logging). 

If you have further questions, please contact [Pivotal Support](https://support.pivotal.io/). Thank you.
