### ISSUE TITLE
Need information on HeapDump collection in "using-spring-boot-actuator-integrations-with-pivotal-cloud-foundry"

### ISSUE THREAD

**Issue by rahulvijay24feb** [pivotal-cf/docs-pivotalcf-console#9]
The Heap Dump section in https://content.pivotal.io/blog/using-spring-boot-actuator-integrations-with-pivotal-cloud-foundry-111   explains "just click the three vertical dots next to one of your application's instances and select Heap Dump".

Assuming that we can collect HeapDumps on individual instances, I see no "3 vertical dots" next to my application instances. Can you please help if I am missing something here ? A screen shot in the documentation would be really helpful.

**Comment by ljarzynski** [comment]
@rahulvijay24feb I think I found what you're looking for... See the "Download Heap Dump" section of the "Using Spring Boot Actuators with Apps Manager" documentation (from the official PCF docs): https://docs.pivotal.io/pivotalcf/1-11/console/using-actuators.html#view-heap.

**Comment by rahulvijay24feb** [comment]
@ljarzynski  : Thank you for pointing it out. Unfortunately I dont see the vertical dots as in the screenshot on the instances of my spring boot app which has the actuator dependency and is deployed on pivotal cloud founry

**Comment by rahulvijay24feb** [comment]
@ljarzynski : Looks like I have the Gap was me having PCF 1.10 .
